### ISSUE TITLE
cant save html/image

### ISSUE THREAD

**Issue by clearlyqt** [kelpso/kanjigrid#2]
error and crashes when trying to save html/image

Caught exception:
Traceback (most recent call last):
  File "C:\Users\xxxxxx\AppData\Roaming\Anki2\addons21\1469765093\__init__.py", line 290, in <lambda>
    sh = QPushButton("Save HTML", clicked=lambda: self.savehtml(config))
  File "C:\Users\xxxxxx\AppData\Roaming\Anki2\addons21\1469765093\__init__.py", line 302, in savehtml
    fileName = QFileDialog.getSaveFileName(self.win, "Save Page", QStandardPaths.standardLocations(QStandardPaths.DesktopLocation)[0], "Web Page (*.html *.htm)")[0]
AttributeError: type object 'QStandardPaths' has no attribute 'DesktopLocation'

**Comment by clearlyqt** [comment]
found a workaround, if i just delete the QStandardPaths.standardLocation(QStandardPaths.DesktopLocation) from line 302 it allows me to save the html anywhere, if i remove it in 315 its still broken for the image though

**Comment by BigBoyBarney** [comment]
Can confirm this change fixes the export issue for me as well, using:
- Anki 24.04.1 (Flatpak version)
- Fedora 39

Starting from line 301:
```diff
[…]
def savehtml(self, config):
+	fileName = QFileDialog.getSaveFileName(self.win, "Save Page", "Web Page (*.html *.htm)")[0]
-	fileName = QFileDialog.getSaveFileName(self.win, "Save Page",QStandardPaths.standardLocation(QStandardPaths.DesktopLocation)[0], "Web Page (*.html *.htm)")[0]
        if fileName != "":
[…]
```

Maybe this change breaks something else, but so far I haven't encountered any issues.
